# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restfulusers_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
