# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restfulusers_app', '0002_auto_20171017_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
