# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninjas',
            old_name='Dojos',
            new_name='dojos',
        ),
    ]
